name: "Deploy NFT Quest Testnet"
on:
  push:
    branches: [ "main" ]
    paths:
      - "examples/nft-quest/**"
      - "packages/sdk/**"
  workflow_dispatch:

env:
  HUSKY: 0
  CI: true
  NUXT_PUBLIC_GTAG_ID: ${{ secrets.NFT_QUEST_ANALYTICS_ID }}

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4
        with:
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -r --frozen-lockfile

      # SDK depends on contracts
      - name: Install contract dependencies
        run: pnpm install -r --frozen-lockfile
        working-directory: packages/contracts

      - name: Build contracts
        run: pnpm build
        working-directory: packages/contracts

      # Local node to have target for deploy
      - name: Era Test Node Action
        uses: dutterbutter/anvil-zksync-action@v1.1.0
        with:
          releaseTag: 'v0.6.1'

      - name: Deploy contracts
        run: pnpm run deploy --file ../auth-server/stores/local-node.json
        working-directory: packages/contracts

      - name: Build apps
        run: pnpm nx build nft-quest

      - name: Deploy firebase hosting
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_NFT_QUEST_TESTNET }}"
          projectId: nft-quest-testnet
          target: nft-quest-testnet
          channelId: live
